In [17]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)

print('shape')
print(a.shape)
print(a.ndim)

type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape
(3, 5)
2


numpy.ndarray

In [26]:
b = np.array([1,2,3,5,6])
print(b)
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[1 2 3 5 6]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [31]:
arr = np.array([20,30,40,50])
arr1 = np.arange(4)
print(arr1)
c = arr - arr1
print(c)

d = arr + arr1
print(d)

[0 1 2 3]
[20 29 38 47]
[20 31 42 53]


In [35]:
B = np.arange(5)
print(B)
print(np.exp(B))

[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [45]:
C = np.arange(5)**3
print(C)

def f(x):
    print(id(x))

f(C)


for i in C:
    print(i**(1/3))

[ 0  1  8 27 64]
140161311831344
0.0
1.0
2.0
3.0
3.9999999999999996


In [50]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
print(a.transpose())
print(np.trace(a))


[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
5.0
