In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
a + 1
2**a

array([ 2,  4,  8, 16])

In [2]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [3]:
j = np.arange(5)
print(j)
print(2**(j + 1))
2**(j + 1) - j

[0 1 2 3 4]
[ 2  4  8 16 32]


array([ 2,  3,  6, 13, 28])

In [4]:
c = np.ones((3, 3))
print(c * c) # not matrix multiplication ....
c.dot(c) # Matrix multiplicaiton..

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [5]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(a == b)
a > b

[False  True False  True]


array([False, False,  True, False], dtype=bool)

In [6]:
np.array_equal(a, b) # Array-Wise Comarison

False

In [7]:
a = np.arange(16).reshape(4, 4)
print(a)
print("*"*15)
print(np.triu(a))
print("*"*15)
print(np.tril(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
***************
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  0 10 11]
 [ 0  0  0 15]]
***************
[[ 0  0  0  0]
 [ 4  5  0  0]
 [ 8  9 10  0]
 [12 13 14 15]]


In [8]:
np.sum(a)

120

In [9]:
x = np.array([[1, 1], [2, 2]])
print(x)
x.sum(axis=1)

[[1 1]
 [2 2]]


array([2, 4])

In [21]:
#x = np.array([1, 3, 5])
x = np.arange(20).reshape(4, 5)
print(x.min())
print(x.max())
x.argmax()

0
19


19

In [23]:
np.all([True, False])

False

In [31]:
np.any([1, 2, 0])

True

In [41]:
a = np.array([3,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all()

False